"""empty message

Revision ID: efe51d8ffa2a
Revises: 
Create Date: 2024-07-23 23:00:58.662876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe51d8ffa2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id_farmer', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('user_password', sa.String(length=100), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('user_birth', sa.Date(), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('farm_address', sa.String(length=255), nullable=False),
    sa.Column('animal_types', sa.String(length=255), nullable=True),
    sa.Column('license_number_farmer', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number_farmer'),
    sa.UniqueConstraint('user_id_farmer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farmers')
    # ### end Alembic commands ###
