"""empty message

Revision ID: 1b9c102bf77a
Revises: 
Create Date: 2024-07-25 20:40:41.838866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b9c102bf77a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veterinarians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veterinarians_id'), 'veterinarians', ['id'], unique=False)
    op.create_index(op.f('ix_farmers_id'), 'farmers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farmers_id'), table_name='farmers')
    op.drop_index(op.f('ix_veterinarians_id'), table_name='veterinarians')
    op.drop_table('veterinarians')
    # ### end Alembic commands ###
